MVC.ECommerce/MVC.ECommerce/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.ECommerce.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC.ECommerce/MVC.ECommerce/Areas/Admin/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.ECommerce.BLL.Services.Abstract;
using MVC.ECommerce.PublicServices.Abstract;
using MVC.ECommerce.Repository._UnitOfWork.Abstract;
using MVC.ECommerce.DAL.Data;
using System.IO;

namespace MVC.ECommerce.Areas.Admin.Controllers
{
    public class MediaController : _BaseController
    {
        int pageSize = 5;
        protected ILogging _log;

        public MediaController(IUnitOfWork uow, IFactory f, ICollect collect,ILogging log) : base(uow, f, collect)
        {
            _log = log;
        }

        IEnumerable<MediaUpload> model = new List<MediaUpload>();
        // GET: Admin/Media
        public ActionResult FileManager(int? Page)
        {
            int _sayfaNo = Page ?? 1;
            ViewBag.currentPage = _sayfaNo;
            model = _uow.GetRepo<MediaUpload>()
                .GetList()
                .OrderByDescending(x => x.Id)
                .Skip((_sayfaNo - 1) * pageSize)
                .Take(pageSize);
            return View(model);
        }

        [HttpPost]
        public ActionResult FileManager(int Page)
        {
            var model = _uow.GetRepo<MediaUpload>()
                .GetList()
                .OrderByDescending(x => x.Id)
                .Skip((Page - 1) * 5)
                .Take(5);

            return PartialView("_FileManagerTable", model);
        }


        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> items)
        {
            MediaUpload media = new MediaUpload();

            foreach (HttpPostedFileBase item in items)
            {
                string uniqueFileName = Guid.NewGuid().ToString();
                string extention = Path.GetExtension(item.FileName);
                string fullFileName = HttpContext.Server.MapPath("/Media/Images/" + uniqueFileName + extention);
                item.SaveAs(fullFileName);
                media.Name = uniqueFileName + extention;
                media.Path = "/Media/Images/" + uniqueFileName + extention;

                _uow.GetRepo<MediaUpload>()
                    .Add(media);
            }
            try
            {
                if (_uow.Commit() > 0)
                    return RedirectToAction("FileManager");
                else
                {
                    TempData["Msg"] = "Bir hata oluştu!";
                    return View();
                }
            }
            catch(Exception ex)
            {
                _log.ProgramLogging(ex.Message);
                
                _uow.Commit();
                TempData["Msg"] = "Bir hata oluştu!";
                return View();
            }
        }

        public JsonResult DeleteUpload(string Secilenler)
        {
            string[] model = Secilenler.Split(' ');

            foreach (string item in model)
            {
                _uow.GetRepo<MediaUpload>()
                    .Delete(Convert.ToInt32(item));
            }
            _uow.Commit();

            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

MVC.ECommerce/MVC.ECommerce/Areas/Admin/Controllers/MessageController.cs
using MVC.ECommerce.DAL.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.ECommerce.BLL.Services.Abstract;
using MVC.ECommerce.PublicServices.Abstract;
using MVC.ECommerce.Repository._UnitOfWork.Abstract;

namespace MVC.ECommerce.Areas.Admin.Controllers
{
    public class MessageController : _BaseController
    {

        int pageSize=20;

        public MessageController(IUnitOfWork uow, IFactory f, ICollect collect) : base(uow, f, collect)
        {
        }

        public ActionResult Inbox(int? page)
        {

            int sayfaNo = page ?? 1;

            var model =
                _uow.GetRepo<Message>()
                .Where(x => x.IsDeleted == false)
                .Skip((sayfaNo-1)*pageSize)
                .Take(pageSize);

            return View(model);
        }

        [HttpPost]
        public JsonResult Inbox(string Secilenler)
        {
            string[] model = Secilenler.Split(' ');
            foreach (string item in model)
            {
                _uow.GetRepo<Message>()
                    .GetById(Convert.ToInt32(item))
                    .IsRead = true;
            }
            //_uow.Commit();
            return Json(model);
        }

        public ActionResult TrashBox()
        {
            IEnumerable<Message> model = _uow
                .GetRepo<Message>()
                .Where(x => x.IsDeleted == true);
            return View(model);
        }

        public JsonResult DeleteInbox(string Secilenler)
        {
            if (Secilenler != "")
            {
                string[] model = Secilenler.Split(' ');
                Message msg = new Message();

                foreach (var item in model)
                {
                    msg = _uow.GetRepo<Message>()
                        .GetById(Convert.ToInt32(item));
                    msg.IsDeleted = true;
                    msg.IsRead = true;
                }

                _uow.Commit();
                return Json(model, JsonRequestBehavior.AllowGet);
            }
            else
                return Json("Silinecek öge bulunamadı!", JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteTrash(string Secilenler)
        {
            string[] model = Secilenler.Split(' ');
            foreach (string item in model)
            {
                _uow.GetRepo<Message>()
                    .Delete(Convert.ToInt32(item));
            }
            _uow.Commit();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

    }
}

MVC.ECommerce/MVC.ECommerce/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.ECommerce.BLL.Services.Abstract;
using MVC.ECommerce.PublicServices.Abstract;
using MVC.ECommerce.Repository._UnitOfWork.Abstract;
using MVC.ECommerce.DAL.Data;
using MVC.ECommerce.BLL.Validations.ProductValidator;
using FluentValidation.Results;
using MVC.ECommerce.DAL.Model;
using System.IO;

namespace MVC.ECommerce.Areas.Admin.Controllers
{
    public class ProductController : _BaseController
    {

        int productId;
        int pageSize = 20;
        protected ILogging _log;

        public ProductController(IUnitOfWork uow, IFactory f, ICollect collect, ILogging log) : base(uow, f, collect)
        {
            _log = log;
        }

        #region Ürün Listeleme
        public ActionResult List(int? page)
        {
            int sayfaNo = page ?? 1;  
                
            var model =
                _uow
                .GetRepo<Product>()
                .Where(x => x.IsDeleted == false);
            int totalPage = (int)Math.Ceiling((decimal)(model.Count() / pageSize));

            model
                .Skip(pageSize * (sayfaNo - 1))
                .Take(pageSize);

            if (pageSize <= model.Count())
                TempData["ListCount"] = totalPage;
            return View(model);
        }

        [HttpPost]
        public ActionResult List(int page)
        {


            return PartialView("_ProductList");
        }
        #endregion

        #region Ürün Ekleme Alanı
        public ActionResult Add()
        {
            ViewBag.Categories = CategoryFill();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ProductAddModel model)
        {

            if (ModelValidate(model.Product).IsValid)
            {
                _uow.GetRepo<Product>().Add(model.Product);
                try
                {
                    if (_uow.Commit() > 0)
                    {                      
                        productId =
                            _uow.GetRepo<Product>()
                            .GetList()
                            .OrderByDescending(x => x.Id)
                            .FirstOrDefault()
                            .Id;
                        ModelState.Clear();

                        if (model.UploadedProductPic != null)
                        {
                            foreach (HttpPostedFileBase item in model.UploadedProductPic)
                            {
                                string uniqueFileName = Guid.NewGuid().ToString();
                                string extention      = Path.GetExtension(item.FileName);
                                string fullFileName   = HttpContext.Server.MapPath("/Media/Images/" + uniqueFileName + extention);
                                item.SaveAs(fullFileName);

                                model.ProductPics.ProductId = productId;
                                model.ProductPics.Name      = uniqueFileName + extention;
                                model.ProductPics.Path      = "/Media/Images/" + uniqueFileName + extention;

                                ProductPics pics = new ProductPics()
                                {
                                    ProductId = model.ProductPics.ProductId,
                                    Name      = model.ProductPics.Name,
                                    Path      = model.ProductPics.Path
                                };

                                _uow.GetRepo<ProductPics>()
                                    .Add(pics);
                            }

                            _uow.Commit();
                        }
                        TempData["Msg"] = "Başarıyla eklenmiştir.";
                    }
                    else
                    {
                        TempData["Msg"] = "Bir hata oluştu!";
                        return View();
                    }
                }
                catch (Exception ex)
                {
                    _log.ProgramLogging(ex.Message);

                };

                return View();
            }
            else
                _collect.CollectError<ProductValidator, Product>(model.Product);
            ViewBag.Categories = CategoryFill();
            return View();
        }
        #endregion

        #region Ürün Güncelleme Alanı
        public ActionResult Update(int id)
        {
            Product model =
                _uow.GetRepo<Product>()
                .GetById(id);

            return View(model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(ProductAddModel model)
        {
            if (ModelValidate(model.Product).IsValid)
            {
                _uow.GetRepo<Product>().Update(model.Product);
                try
                {
                    if (_uow.Commit() > 0)
                    {
                        TempData["Msg"] = "Başarıyla güncellenmiştir.";
                        ModelState.Clear();
                    }
                }
                catch (Exception ex)
                {
                    TempData["Msg"] = "Bir hata oluştu";
                    _log.ProgramLogging(ex.Message);
                    _uow.Commit();
                }

            }
            else
                _collect.CollectError<ProductValidator, Product>(model.Product);

            return View();
        }
        #endregion

        #region Ürün Silme Alanı
        public ActionResult Delete(int id)
        {
            _uow.GetRepo<Product>().Delete(id);
            _uow.Commit();

            return RedirectToAction("List");
        }
        #endregion

        #region Model Doğrulama Fonksiyonu
        private ValidationResult ModelValidate(Product model)
        {
            return _f.Create<ProductValidator, Product>(model);
        }
        #endregion

        #region Kategori Doldurma
        private List<SelectListItem> CategoryFill()
        {
            List<SelectListItem> cat = new List<SelectListItem>();

            _uow
                .GetRepo<Category>()
                .GetList()
                .ForEach(x => cat.Add
                (
                    new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    })
                 );

            return cat;
        }
        #endregion

    }
}

MVC.ECommerce/MVC.ECommerce/Areas/Admin/Views/Shared/_LayoutPage.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta -->
    <meta name="description" content="Premium Quality and Responsive UI for Dashboard.">
    <meta name="author" content="ThemePixels">

    <title>Yönetici Paneli</title>
    @Styles.Render("~/bundlesAdmin/styles")
    @RenderSection("styles",false)
</head>
<body>
    <!-- ##### SIDEBAR LOGO ##### -->
    <div class="kt-sideleft-header">
        <div class="kt-logo"><a href="/Dashboard/Index/">Yönetici Paneli</a></div>
        <div id="ktDate" class="kt-date-today"></div>
        <div class="input-group kt-input-search">
            <input type="text" class="form-control" placeholder="Ara...">
            <span class="input-group-btn mg-0">
                <button class="btn"><i class="fa fa-search"></i></button>
            </span>
        </div><!-- input-group -->
    </div>

    @Html.Partial("_leftSidebar")
    @Html.Partial("_headPanel")
   

    <div class="kt-breadcrumb">
        <nav class="breadcrumb">
            @Html.ActionLink("Anasayfa","Index","Dashboard",new { @class="breadcrumb-item"})
            @RenderSection("links",false)
        </nav>
    </div><!-- kt-breadcrumb -->

        
        @RenderBody()


    @Scripts.Render("~/bundlesAdmin/scripts")
    @RenderSection("scripts",false)
</body>
</html>

MVC.ECommerce/MVC.ECommerce/Areas/Admin/Views/Shared/_headPanel.cshtml

<div class="kt-headpanel">
    <div class="kt-headpanel-left">
        <a id="naviconMenu" href="" class="kt-navicon d-none d-lg-flex"><i class="icon ion-navicon-round"></i></a>
        <a id="naviconMenuMobile" href="" class="kt-navicon d-lg-none"><i class="icon ion-navicon-round"></i></a>
    </div><!-- kt-headpanel-left -->
    <div class="kt-headpanel-right">
        <div class="dropdown dropdown-notification">
            <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
                <i class="icon ion-ios-bell-outline tx-24"></i>
                <!-- start: if statement -->
                <span class="square-8 bg-danger pos-absolute t-15 r-0 rounded-circle"></span>
                <!-- end: if statement -->
            </a>
            <div class="dropdown-menu wd-300 pd-0-force">
                <div class="dropdown-menu-header">
                    <label>BİLDİRİMLER</label>
                    <a href="">Tümünü Okundu Olarak İşaretle</a>
                </div><!-- d-flex -->
                <div class="media-list">
                    <!-- loop starts here -->
                    <a href="" class="media-list-link read">
                        <div class="media pd-x-20 pd-y-15">
                            <img src="/Content/Admin/img/img8.jpg" class="wd-40 rounded-circle" alt="">
                            <div class="media-body">
                                <p class="tx-13 mg-b-0"><strong class="tx-medium">Suzzeth Bungaos</strong> tagged you and 18 others in a post.</p>
                                <span class="tx-12">October 03, 2017 8:45am</span>
                            </div>
                        </div><!-- media -->
                    </a>
                    <!-- loop ends here -->
                    <a href="" class="media-list-link read">
                        <div class="media pd-x-20 pd-y-15">
                            <img src="/Content/Admin/img/img9.jpg" class="wd-40 rounded-circle" alt="">
                            <div class="media-body">
                                <p class="tx-13 mg-b-0"><strong class="tx-medium">Mellisa Brown</strong> appreciated your work <strong class="tx-medium">The Social Network</strong></p>
                                <span class="tx-12">October 02, 2017 12:44am</span>
                            </div>
                        </div><!-- media -->
                    </a>
                    <a href="" class="media-list-link read">
                        <div class="media pd-x-20 pd-y-15">
                            <img src="/Content/Admin/img/img10.jpg" class="wd-40 rounded-circle" alt="">
                            <div class="media-body">
                                <p class="tx-13 mg-b-0">20+ new items added are for sale in your <strong class="tx-medium">Sale Group</strong></p>
                                <span class="tx-12">October 01, 2017 10:20pm</span>
                            </div>
                        </div><!-- media -->
                    </a>
                    <a href="" class="media-list-link read">
                        <div class="media pd-x-20 pd-y-15">
                            <img src="/Content/Admin/img/img5.jpg" class="wd-40 rounded-circle" alt="">
                            <div class="media-body">
                                <p class="tx-13 mg-b-0"><strong class="tx-medium">Julius Erving</strong> wants to connect with you on your conversation with <strong class="tx-medium">Ronnie Mara</strong></p>
                                <span class="tx-12">October 01, 2017 6:08pm</span>
                            </div>
                        </div><!-- media -->
                    </a>
                    <div class="media-list-footer">
                        <a href="" class="tx-12"><i class="fa fa-angle-down mg-r-5"></i> Tüm Bildirimleri Göster</a>
                    </div>
                </div><!-- media-list -->
            </div><!-- dropdown-menu -->
        </div><!-- dropdown -->
        <div class="dropdown dropdown-profile">
            <a href="" class="nav-link nav-link-profile" data-toggle="dropdown">
                <img src="/Content/Admin/img/img3.jpg" class="wd-32 rounded-circle" alt="">
                <span class="logged-name"><span class="hidden-xs-down">Jane Doe</span> <i class="fa fa-angle-down mg-l-3"></i></span>
            </a>
            <div class="dropdown-menu wd-200">
                <ul class="list-unstyled user-profile-nav">
                    <li><a href=""><i class="icon ion-ios-person-outline"></i>Profil Düzenle</a></li>
                    <li><a href=""><i class="icon ion-ios-gear-outline"></i> Ayarlar</a></li>
                    <li><a href=""><i class="icon ion-ios-download-outline"></i> Yüklemeler</a></li>
                    <li><a href=""><i class="icon ion-ios-star-outline"></i> Favoriler</a></li>
                    <li><a href=""><i class="icon ion-ios-folder-outline"></i> Collections</a></li>
                    <li><a href=""><i class="icon ion-power"></i>Çıkış Yap</a></li>
                </ul>
            </div><!-- dropdown-menu -->
        </div><!-- dropdown -->
    </div><!-- kt-headpanel-right -->
</div><!-- kt-headpanel -->

MVC.ECommerce/MVC.ECommerce/Areas/Admin/Views/Shared/_leftSidebar.cshtml


<div class="kt-sideleft">
    <label class="kt-sidebar-label">Navigation</label>
    <ul class="nav kt-sideleft-menu">
        <li class="nav-item">
            <a href="index.html" class="nav-link">
                <i class="icon ion-ios-home-outline"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- nav-item -->

        <li class="nav-item">
            <a href="" class="nav-link with-sub">
                <i class="icon ion-ios-briefcase-outline"></i>
                <span>Üst Kategoriler</span>
            </a>
            <ul class="nav-sub">
                <li class="nav-item">
                    @Html.ActionLink("Üst Kategori Ekle", "Add", "UpCategory", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Listele", "List", "UpCategory", null, new { @class = "nav-link" })
                </li>
            </ul>
        </li><!-- nav-item -->

        <li class="nav-item">
            <a href="" class="nav-link with-sub">
                <i class="icon ion-clipboard"></i>
                <span>Kategoriler</span>
            </a>
            <ul class="nav-sub">
                <li class="nav-item">
                    @Html.ActionLink("Kategori Ekle", "Add", "Category", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Tümünü Listele", "List", "Category", null, new { @class = "nav-link" })
                </li>
            </ul>
        </li><!-- nav-item -->

        <li class="nav-item">
            <a href="" class="nav-link with-sub">
                <i class="icon ion-ios-cart"></i>
                <span>Ürünler</span>
            </a>
            <ul class="nav-sub">
                <li class="nav-item">
                    @Html.ActionLink("Ürün Ekle", "Add", "Product", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Tümünü Listele", "List", "Product", null, new { @class = "nav-link" })
                </li>
            </ul>
        </li><!-- nav-item -->

        <li class="nav-item">
            <a href="" class="nav-link with-sub">
                <i class="icon ion-chatbox"></i>
                <span>Yorumlar</span>
            </a>
            <ul class="nav-sub">
                <li class="nav-item"><a href="accordion.html" class="nav-link">Tüm Yorumlar</a></li>
                <li class="nav-item"><a href="alerts.html" class="nav-link">Tümünü Listele</a></li>
            </ul>
        </li><!-- nav-item -->

        <li class="nav-item">
            <a href="" class="nav-link with-sub">
                <i class="icon ion-person-stalker"></i>
                <span>Kullanıcılar</span>
            </a>
            <ul class="nav-sub">
                <li class="nav-item"><a href="accordion.html" class="nav-link">Kullanıcı Ekle</a></li>
                <li class="nav-item"><a href="alerts.html" class="nav-link">Tümünü Listele</a></li>
            </ul>
        </li><!-- nav-item -->

        <li class="nav-item">
            <a href="" class="nav-link with-sub">
                <i class="icon ion-ios-upload-outline"></i>
                <span>Dosya Yöneticisi</span>
            </a>
            <ul class="nav-sub">
                <li class="nav-item">
                    @Html.ActionLink("Medya", "FileManager", "Media",null, new { @class = "nav-link" })
                </li>
            </ul>
        </li><!-- nav-item -->

        <li class="nav-item">
            <a href="" class="nav-link with-sub">
                <i class="icon ion-ios-email-outline"></i>
                <span>Mesajlar</span>
            </a>
            <ul class="nav-sub">
                <li class="nav-item">
                    @Html.ActionLink("Gelen Kutusu","Inbox", "Message", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Çöp Kutusu", "Thrashbox", "Message", null, new { @class = "nav-link" })
                </li>
            </ul>
        </li><!-- nav-item -->

    </ul>


</div><!-- kt-sideleft -->